import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import { Span } from "next/dist/trace";
import { BsHeartPulse, BsPeople } from "react-icons/bs";
import { MdOutlineChevronRight } from "react-icons/md";
import { RiMentalHealthLine } from "react-icons/ri";
import { IoSettingsOutline } from "react-icons/io5";
import { CiSettings } from "react-icons/ci";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <div className={styles.sideBar}>
          <div className={styles.title}>HealthHub</div>

          <div className={styles.menu}>Main menu</div>
          <div className={styles.DashboardBox}>
            <BsHeartPulse />
            <span className={styles.menuItems}>Dashboard</span>
          </div>
          <div className={styles.menuBox}>
            <BsPeople />
            <span className={styles.menuItems}>Patients</span>
          </div>
          <div className={styles.firstChevron}>
            <MdOutlineChevronRight />
            <span className={styles.MenuSubItems}>Add patients</span>
          </div>
          <div className={styles.chevrons}>
            <MdOutlineChevronRight />
            <span className={styles.MenuSubItems}>Add Clinic patient</span>
          </div>
          <div className={styles.chevrons}>
            <MdOutlineChevronRight />
            <span className={styles.MenuSubItems}>All patients</span>
          </div>
          <div className={styles.menuBox}>
            <RiMentalHealthLine />
            <span className={styles.menuItems}>Patients</span>
          </div>
          <div className={styles.firstChevron}>
            <MdOutlineChevronRight />
            <span className={styles.MenuSubItems}>Add Drugs</span>
          </div>
          <div className={styles.chevrons}>
            <MdOutlineChevronRight />
            <span className={styles.MenuSubItems}>Inventory</span>
          </div>

          <div className={styles.other}>Other</div>
          <div className={styles.SettingsBox}>
            <CiSettings />
            <span className={styles.menuItems}>Settings</span>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
